### ISSUE TITLE
links encoded with &#x2F;

### ISSUE THREAD

**Issue by yarekc** [Hypercontext/linkifyjs#219]
In many JS texts treatments, links html are encoded like :

`https:&#x2F;&#x2F;html5-chat.com&#x2F;`

Any idea on how handle these cases ?

**Comment by nfrasser** [comment]
Linkify's HTML interface http://soapbox.github.io/linkifyjs/docs/linkify-html.html should theoretically handle this, but HTML character encoding support is temporarily disabled in the built-in HTML parser. This may be fixed in a future release.

**Comment by ptandler** [comment]
I stepped over this issue, but I think in my case I would expect a different result, because my URL is _followed_ by a HTML character reference, that is not part of the URL and gets broken:

```
const linkifyHtml = require('linkifyjs/html'); // v2.1.6

const html = "&quot;http://xml.evernote.com/pub/enml2.dtd&quot;";
const out = linkifyHtml(html, {nl2br: true, className: "", target: ""})
console.info(out);
// Generates:
// &quot;<a href="http://xml.evernote.com/pub/enml2.dtd&quot">http://xml.evernote.com/pub/enml2.dtd&quot</a>;
//
// but in this case I would expect that the following HTML character reference is not destroyed:
// &quot;<a href="http://xml.evernote.com/pub/enml2.dtd&quot">http://xml.evernote.com/pub/enml2.dtd</a>&quot;
```

Actually, I've no idea how these two cases can be automatically distinguished. Maybe add an option?

-> Should I open a new issue for this or would you regard this as related?

**Comment by nfrasser** [comment]
Fixed in the latest [Linkify v4](https://github.com/Hypercontext/linkifyjs/releases/tag/v4.0.0)
