### ISSUE TITLE
Homograph attack

### ISSUE THREAD

**Issue by zxlin** [Hypercontext/linkifyjs#280]
## Issue

This lib, even the Github viewer itself, is vulnerable to a homograph attack - meaning that we can leverage a seemingly innocent link e.g. `http://ebаy.com` to redirect users to actually `http://xn--eby-7cd.com`

Imagine if a user posts a link like this into a forum and has other susceptible users click on it. 

Homograph normalized: http://ebаy.com (hover over the URL to see the browser decode the URL)

Actual equivalent IDN (punycode): http://xn--eby-7cd.com

## Further reading

https://en.wikipedia.org/wiki/IDN_homograph_attack

## Potential remediation
https://en.wikipedia.org/wiki/IDN_homograph_attack#Defending_against_the_attack

We can leverage punycode (https://en.wikipedia.org/wiki/Punycode) to display the URL instead of the normalized URL. This could be a configurable option for the lib so the user of the lib can choose their risk profile. But I would recommend setting the use of punycode to true by default so we can avoid the security issue as described. 

https://www.npmjs.com/package/punycode is a popular lib for JS. 

Originally reported by @Mik317 to our security program

**Comment by zxlin** [comment]
Would you recommend leveraging the format option or building something into the lib to handle this issue?

**Comment by nfrasser** [comment]
Using punycode with the `format` option will definitely help with this kind of attack. However, Linkify's ultimate purpose is finding URLs, not figuring out which URLs are secure. 

In future releases I can foresee a `hasIDN` option, which may be used to indicate that a domain has homographs. This would be implemented with IDN domain support (#92). Otherwise Punycode will not be built into Linkify.

**Comment by nfrasser** [comment]
Closing as out of scope
