### ISSUE TITLE
Linkify treats ideographic space characters as part of URLs

### ISSUE THREAD

**Issue by igoshawk** [Hypercontext/linkifyjs#315]
I found this issue when I'm using linkify for URLs in Japanese text and the spaces in Japanese are ideographic spaces (full-width). LinkifyHtml is converting the URL and text with an ideographic space in between as one big URL instead of one URL and text.

The text I'm using:
```
https://google.com　　　　　　　テスト
```

The Unicode for ideographic space is `\u3000`.

Not sure whether the other whitespaces should be treated the same as normal whitespaces, or should be considered as part of the URL.

**Comment by YuikoIto** [comment]
I think this problem is occurred because linkifyjs is not supported for double-byte whitespaces.
I checked if the problem still happen when I use one-byte whitespace (normal whitespace), then found nothing strange happened.
So you may be able to fix this by writing a regular expression that also takes into account double-byte whitespaces...

**Comment by nfrasser** [comment]
Fixed in v3.0.0 (#318)
