### ISSUE TITLE
Inconsistent detection with or without protocol

### ISSUE THREAD

**Issue by TongLing916** [Hypercontext/linkifyjs#434]
I have noticed that the link detection is somehow different when the link starts with `https://` or sth like that, is it done on purpose?  Like the image below, when the link starts with `https://`, the numbers at the end are also considered part of the link.

<img width="1355" alt="Screenshot 2023-03-15 at 15 01 00" src="https://user-images.githubusercontent.com/19634029/225231939-887162da-a6fd-4a9f-adee-2b473cd9204d.png">

**Comment by nfrasser** [comment]
Hi @TongLing916, yes this is by design. Linkify considers everything following a protocol `http://...` to be part of the URL (except for whitespace and a few other special characters). This is to support exotic custom or domain-specific URLs - there could conceivably be an environment where `http://www.google.com123` resolves to a valid URL.

However, when a protocol is not included, Linkify can only detect more conventional URL styles such as those that end in `.com` in order to avoid false positives.

Hope that clarifies it.
