### ISSUE TITLE
Linkified URL containing double quotes fails to include the last one and puts it outside of the anchor tag

### ISSUE THREAD

**Issue by taroy1** [Hypercontext/linkifyjs#469]
When I linkify the following URL:

`http://example.com?search={"max":"12"}`

it comes back as:

`<a href="http://example.com?search={&quot;max&quot;:&quot;12">http://example.com?search={"max":"12</a>"}`

rather than the expected:

`<a href="http://example.com?search={&quot;max&quot;:&quot;12&quot;}">http://example.com?search={"max":"12"}</a>`

Observe that the last double quote and curly brace are outside of the anchor tag. The result is an incomplete href.

**Comment by nfrasser** [comment]
Raw unencoded quotes are not valid URL query string characters. Due to this and other technical parsing constrains, Linkify cannot provide support for these (notice that GitHub's formatter doesn't detect these as expected either).

A correctly encoded URL does work with linkify, e.g.,: http://example.com/?search={%22max%22:%2212%22}
